<?php
/**
 * @file
 * producto_sngr.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function producto_sngr_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_coordinacion_producto'.
  $field_bases['field_coordinacion_producto'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_coordinacion_producto',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 200,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_involucrados_producto'.
  $field_bases['field_involucrados_producto'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_involucrados_producto',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 200,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
